name: "Nette Tester"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  coverage:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-coverage.yml@v1
    with:
      php: "8.2"
      make: "init coverage"
